apiVersion: v1
kind: Service
metadata:
  name: flasknginx-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: flasknginx
  ports:
    - port: 8000
      targetPort: 8085

# kubectl apply -f loadbalancerService.yml
# kubectl get service
# BROWSER: externalIP:port
# kubectl delete service flasknginx-loadbalancer