apiVersion: v1
kind: Service
metadata:  
  name: flasknginx-nodeportservice
spec:
  type: NodePort
  selector:    
    app: flasknginx
  ports:  
  - port: 8085
    targetPort: 8085
    nodePort: 30036