apiVersion: v1
kind: Service
metadata:
  name: flasknginx-service
spec:
  ports:
  - port: 8085
    targetPort: 8085
    name: http
  selector:
    app: flasknginx

#kubectl apply -f kuber.yml 
#kubectl get services    
#kubectl port-forward svc/flasknginx-service 8085:8085