apiVersion: v1
kind: Service
metadata:
  name: flasknginx-service
spec:
  ports:
  - port: 8085
    targetPort: 8085
    name: http
  selector:
    app: flasknginx

#-----TESTING ONLY-----
#kubectl apply -f simpleService.yml
#kubectl get services    
#kubectl port-forward svc/flasknginx-service 8085:8085
#Browser http://localhost:8085/
#kubectl delete service flasknginx-service
